FROM ubuntu:22.04 as base

ENV DEBIAN_FRONTEND=noninteractive

RUN set -e -x ;\
    apt-get -y update ;\
    apt-get -y upgrade ;\
    apt-get -y install \
        build-essential autoconf cmake gcc git ninja-build doxygen python3

RUN set -e -x ;\
    git clone https://gitlab.kitware.com/cmake/cmake.git ;\
    cd cmake && git checkout tags/v3.14.2 ;\
    ./bootstrap && make && make install ;\
