FROM ubuntu:bionic-20190307

ENV DEBIAN_FRONTEND=noninteractive

RUN set -e -x ;\
    apt-get -y update ;\
    apt-get -y upgrade ;\
    apt-get -y install \
        build-essential cmake gcc git ninja-build doxygen python3
